### PR TITLE
Update dependencies to address critical vulnerability in minimist<@1.2.6

### PR DESCRIPTION
**Pull request by daledupreez**
This PR was the result of two steps:
1. Running `npm install -D eslint-config-standard@^17.0.0 eslint-plugin-promise@^6.0.0` to work around some dependency conflicts due to the main package requiring `eslint@^8.0.0` and these packages depending on `eslint@^7.x`
2. Running `npm audit fix`

### CODE REVIEW

**Comment by daledupreez** [comment]
@AllTerrainDeveloper, I noticed this via Dependabot: https://github.com/Automattic/tracks-chrome-extension/security/dependabot/2

Who should we add to the list of people/teams who get the dependabot alerts?

Also, I noticed a dependency on `jslint` in the dependencies -- is that used by anything given that the dev dependencies depend on `eslint`?

**Comment by AllTerrainDeveloper** [comment]
Ups this was solved a couple of days ago and I did not have time to test/review changes. The same issue has been fixed here:
https://github.com/Automattic/tracks-chrome-extension/pull/8

**Comment by AllTerrainDeveloper** [comment]
I think I can be in the list of people who gets the dependabot alerts :) 
JSLINT should not be in the dependencies. I might have added it by mistake. I'll move it as soon as I can find more time in 20% time! :) Thank you for checking it!

**Comment by daledupreez** [comment]
Marking this PR as resolved as this was already addressed in #8.

**Pull request closed without merging**
